### ISSUE TITLE
Unplug 2.2.5.68 works, 2.3.3.12 does not (this one is in the catalog)

### ISSUE THREAD

**Issue by gmaxey** [electric-cloud-community/Unplug#11]
pages/un_run*.xml missing from installation plugins directory.
These files are in .gitignore, suggesting that the installer is supposed to be adding these files.

  <title>unplug 2.3.2.82</title>

Laurent:
I had crated a script to create those (easier than to maintain) 20 indiv, I guess the build process is different on chronic3.
I’ll create them again, and un-ignore them

**Comment by lrochette** [comment]
fixed in 2.3.4
